### PR TITLE
 New 1.7.24 upstream version for noble

### PR DESCRIPTION
**Pull request by athos-ribeiro**

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
This one is currently FTBFS: https://launchpadlibrarian.net/760637050/buildlog_ubuntu-noble-amd64.containerd-app_1.7.24-0ubuntu1~24.04.1~ppa1_BUILDING.txt.gz

**Comment by athos-ribeiro** [comment]
the ftbfs issue here was fixed

**Review by lvoytek — APPROVED** [review]
Looked through all the changes and they look good to me. Upstream matches too

**Comment by toabctl** [comment]
LGTM, too

**Pull request merged**
